export let windows = [
    {
        windowId: 0,
        text: 'The Returnees',
        link: '/discover/cl8vh8rmx4wx80bw26jscwzhn',
        image: 'https://media.graphassets.com/output=format:jpg/f3Vm8RM1QIygtsRpILLT',
        component: 'WindowOne',
        class: 'window-one top-layer window-small',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 1,
        text: 'Spanish Migrant',
        link: '/discover/cl8vc7gt84tx30cuqor5bxqfy',
        image: 'https://media.graphassets.com/n3ASraESNOSwZQunBDFT',
        component: 'WindowOne',
        class: 'window-two top-layer window-small',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 2,
        text: 'A VIP',
        link: '/discover/cl8vjb2rn4x9i0burl532c8t2',
        image: 'https://media.graphassets.com/output=format:jpg/dBy5wDdcTOKiU2XedRIX',
        component: 'WindowOne',
        class: 'window-three top-layer window-small',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 3,
        text: 'Botched Dreams',
        link: '/discover/cl8ysy2yw08zy0bvy1hq4bnkf',
        image: 'https://media.graphassets.com/output=format:jpg/2t4CIKQCRZGycuXT063A',
        component: 'WindowTwo',
        class: 'window-four top-layer window-big',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 4,
        text: 'The Angel',
        link: '/discover/cl8yszk6v08im0bvyodnw9lyy',
        image: 'https://media.graphassets.com/output=format:jpg/9GqMbWjwRgK5qqVEjcRG',
        component: 'WindowTwo',
        class: 'window-five top-layer window-big',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 5,
        text: 'Illegal Demolition',
        link: '/discover/cl8yt1lbr08kt0bvyck52dg6p',
        image: 'https://media.graphassets.com/output=format:jpg/ee5OeSDLTRWLw7M4ZMNT',
        component: 'WindowTwo',
        class: 'window-six top-layer window-big',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 6,
        text: 'Slave Trade',
        link: '/discover/cl8ysx9tz08cs0auqxhojha3y',
        image: 'https://media.graphassets.com/output=format:jpg/1L4voe4TCKFo4WW781gD',
        component: 'WindowThree',
        class: 'window-seven bottom-layer window-small',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 7,
        text: 'Macaulay',
        link: '/discover/cl8vjfmjh4yr00bw7jt60irl9',
        image: 'https://media.graphassets.com/output=format:jpg/5ui5tI0TROswzb83pDPi',
        component: 'WindowThree',
        class: 'window-eight bottom-layer window-small',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 8,
        text: 'A Family House',
        link: '/discover/cl8ysw30o08be0auq4yw1n8tj',
        image: 'https://media.graphassets.com/output=format:jpg/KMfq2AASka3jlpbANiYk',
        component: 'WindowThree',
        class: 'window-nine bottom-layer window-small',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 9,
        text: '3D Model',
        link: '/3d-model',
        image: 'https://media.graphassets.com/n3ASraESNOSwZQunBDFT',
        component: 'Door',
        class: 'door-frame bottom-layer door window-big',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 10,
        text: 'Credits',
        link: '/credits',
        image: 'https://media.graphassets.com/n3ASraESNOSwZQunBDFT',
        component: 'WindowFour',
        class: 'window-ten bottom-layer window-big',
        width: '226px',
        height: '186px',
    },
    {
        windowId: 11,
        text: 'Guestbook',
        link: '/guestbook',
        image: 'https://media.graphassets.com/n3ASraESNOSwZQunBDFT',
        component: 'WindowFour',
        class: 'window-eleven bottom-layer window-big',
        width: '226px',
        height: '186px',
    },
];